name: TheMITBro Formatter

on:
  push:
    paths:
      - "input/**"
      - "src/**"
      - ".github/workflows/formatter.yml"

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install Python packages
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      # Temporary SymPy test
      - name: Test Math Validator
        run: |
          python src/math_validator.py

      # Run formatter
      - name: Run formatter
        run: |
          python src/main.py

      - name: Commit formatted files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add output/

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Auto formatted"
          git push
