name: TheMITBro Formatter

on:
  push:
    paths:
      - "input/**"
      - "src/**"
      - ".github/workflows/formatter.yml"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run formatter
        run: |
          python src/main.py

      - name: Commit formatted files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/
          git diff --cached --quiet || git commit -m "Auto formatted"
          git push
